### ISSUE TITLE
When executing 'coffee index.coffee' I get an EADDRINUSE error

### ISSUE THREAD

**Issue by herbsmn** [taigaio/taiga-events#11]
This is the error I'm getting. I'm assuming some ports are in use and that's interfering, but I don't know which ones or how to stop them.

`events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1158:14)
  at listen (net.js:1184:10)
  at net.js:1282:9
  at dns.js:85:18
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
`

**Comment by herbsmn** [comment]
i'm curious, does taiga-events need to be running in order for the coffee script to run? when i turn off taiga-events the coffee script seems to just hang there. what the output supposed to be after running it?

**Comment by herbsmn** [comment]
I don't know if this helps or not: https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback

**Comment by juanfran** [comment]
if you have a `config.json` the port that throw that error is in `webSocketServer` `port`

**Comment by herbsmn** [comment]
{
    "url": "amqp://taiga:password@localhost:5672/taiga",
    "secret": "theveryultratopsecretkey",
    "webSocketServer": {
        "port": 8888
    }
}

**Comment by herbsmn** [comment]
i tried killing the taiga thing that was using 8888 and then running the coffee script again, but it didn't seem to change anything.

**Comment by juanfran** [comment]
You could run `lsof -i :8888` to see what is using that port. 

if taiga-events outputs nothing means that all is ok.

**Comment by herbsmn** [comment]
great minds think alike! i was just documenting that i had done this over at https://github.com/taigaio/taiga-front/issues/1032

**Comment by herbsmn** [comment]
i really appreciate the super quick response time, btw!

**Comment by herbsmn** [comment]
so taiga-events outputted nothing. how do I test that it is working?

**Comment by juanfran** [comment]
if you are using circus taiga-events should be already running. You can see it with the command `circusctl`

**Comment by herbsmn** [comment]
it is running, but @gregoirelemoulant was saying that his was running but that it still wasn't working.

**Comment by juanfran** [comment]
the easiest way is through taiga-front. For example go to a kanban board and drag an US, you will see the change in other tab. You can also see logs in the browser console like `WebSocket connection opened` `Subscribe to: changes.project.123.userstories`

**Comment by herbsmn** [comment]
i'm unfortunately not seeing the kanban board US change in the other tab.

**Comment by herbsmn** [comment]
i can provide you with any logs you'd like to help debug this issue. let me know what would be of help.

**Comment by herbsmn** [comment]
potentially it is bc i'm using the Tor Browser? I'll check another browser tomorrow. I'm assuming not tho.

**Comment by juanfran** [comment]
could you send us the browser console output? thanks

**Comment by herbsmn** [comment]
is this what you mean?

![screenshot](https://cloud.githubusercontent.com/assets/8562898/16569222/419ced14-4223-11e6-9078-d9cc5096801f.png)

**Comment by herbsmn** [comment]
The Request URL says https. Is it supposed to say wss like this one from taiga.io?

![screen](https://cloud.githubusercontent.com/assets/8562898/16569405/98377b4c-4225-11e6-84d0-433ab514cb58.png)

**Comment by herbsmn** [comment]
![screenshot7](https://cloud.githubusercontent.com/assets/8562898/16569926/1cdc9584-422c-11e6-8409-dd5859c0f6a2.png)

**Comment by herbsmn** [comment]
![screenshot5](https://cloud.githubusercontent.com/assets/8562898/16575751/23d6baa6-427a-11e6-95e7-c040e00510fa.png)

![screenshot732](https://cloud.githubusercontent.com/assets/8562898/16575886/1ee3dbd6-427b-11e6-8426-344da393866f.png)

**Comment by herbsmn** [comment]
![screenshot10](https://cloud.githubusercontent.com/assets/8562898/16576684/4904cb0a-4280-11e6-9c13-1b9cb42a035b.png)

**Comment by herbsmn** [comment]
Heyo! taiga-events is working! it just doesn't work in Tor Browser for some reason.

**Comment by juanfran** [comment]
thanks for the screeshots, it seems all right... :confused:  we have to investigate why in Tor doesn't work

**Comment by herbsmn** [comment]
yeah, sadly next to nothing works on tree.taiga.io when I use the Tor Browser. https://github.com/taigaio/taiga-front/issues/1070#issuecomment-230671269
at least on my own server taiga-events is the only thing that doens't work and other people in my org who don't use the Tor Browser can benefit.
thanks so much for working on this awesome Taiga feature!
that being said, please let me know if I can provide you with any more information as to why Tor Browser isn't working for taiga events.
