### ISSUE TITLE
Uncaught unspecified "error" 

### ISSUE THREAD

**Issue by kapoorabhish** [taigaio/taiga-events#19]
Hello, I have configured taiga successfully with apache, but now I am facing issue with events, below is the error trace. Please help me solve the issue.
```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>:null:null)
    at WebSocket.EventEmitter.emit (events.js:74:15)
    at Receiver.onerror (/home/<username>/taiga-events/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/home/<username>/taiga-events/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/home/<username>/taiga-events/node_modules/ws/lib/Receiver.js:234:43)
    at Receiver.add (/home/<username>/taiga-events/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/home/<username>/taiga-events/node_modules/ws/lib/WebSocket.js:800:20)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
```

**Comment by bameda** [comment]
Can you paste your configuration of taiga-events, rabbitmq and apache (we don't recommend to use apache, by the way)? it seems a connection problem.

**Comment by kapoorabhish** [comment]
Hi bameda,
Thanks for the repsponse.

Below are the configurations.

**taiga-events/config.json**

```
{
    "url": "amqp://taiga:PASSWORD@localhost:5672/taiga",
    "secret": "secret key",
    "webSocketServer": {
        "port": 8888
    }
}
```



**rabbitmq** - Default configuration after installing it through apt-get


**Apache Virtual Host**

```
<VirtualHost *:80>
    ServerName example.com
    ServerAlias www.example.com
    
    DocumentRoot /var/www/html/taiga-front     

    ProxyPass /events/ ws://127.0.0.1:8888/events/
    ProxyPass /admin/ http://127.0.0.1:8000/admin/

    ProxyPass /api/ http://127.0.0.1:8000/api/

    #sym link to taiga-back media
    Alias /media/ /var/www/html/taigamedia/
    
    #sym link to taiga-back static
    Alias /static/ /var/www/html/taigastatic/
    
    <Directory /home/<username>/taiga-front>
        Order deny,allow
        Allow from all
        Options -Indexes
    </Directory>
</VirtualHost>


```

**Comment by bameda** [comment]
Are you sure that rabbitmq is properly configured and is running in the correct port?

**Comment by kapoorabhish** [comment]
Hi bameda

Below is the output of **rabbitmqctl status**
```

Status of node 'rabbit@<hostname>' ...
[{pid,3614},
 {running_applications,[{rabbit,"RabbitMQ","3.2.4"},
                        {os_mon,"CPO  CXC 138 46","2.2.14"},
                        {mnesia,"MNESIA  CXC 138 12","4.11"},
                        {xmerl,"XML parser","1.3.5"},
                        {sasl,"SASL  CXC 138 11","2.3.4"},
                        {stdlib,"ERTS  CXC 138 10","1.19.4"},
                        {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,"Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:6:6] [async-threads:30] [kernel-poll:true]\n"},
 {memory,[{total,41627720},
          {connection_procs,204352},
          {queue_procs,131640},
          {plugins,0},
          {other_proc,13443896},
          {mnesia,79800},
          {mgmt_db,0},
          {msg_index,34384},
          {other_ets,770272},
          {binary,5266848},
          {code,16522377},
          {atom,594537},
          {other_system,4579614}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,5039105638},
 {disk_free_limit,50000000},
 {disk_free,48201609216},
 {file_descriptors,[{total_limit,924},
                    {total_used,7},
                    {sockets_limit,829},
                    {sockets_used,3}]},
 {processes,[{limit,1048576},{used,158}]},
 {run_queue,0},
 {uptime,932}]
...done.
```

One more observation, when I do **telnet localhost 5672**, it gets disconnected after some seconds.
Below is the log entry for it.

```
=INFO REPORT==== 3-Nov-2016::21:57:39 ===
accepting AMQP connection <0.397.0> ([::1]:56266 -> [::1]:5672)

=ERROR REPORT==== 3-Nov-2016::21:57:49 ===
closing AMQP connection <0.397.0> ([::1]:56266 -> [::1]:5672):
{handshake_timeout,handshake}

```

Other than this there is no error in the rabbitmq logs.

**Comment by bameda** [comment]
Try to check the credentials.

Create a file `test_rb_connection.py` and paste this (changin PASSWORD with the valid one):

```
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from kombu import Connection

url = "amqp://taiga:PASSWORD@localhost:5672/taiga"

c = Connection(url)

try:
    c.connect()
except Exception as e:
    print("Exception", e)

if c.connected:
    print("The connection has been stablished.")
    c.close()
else:
    print("ERROR: Whe can connect to", url)
```

and then run

```
workon taiga
python ./test_rb_connection.py
```

**Comment by kapoorabhish** [comment]
Thanks for the ready to use script.

Output is _**The connection has been stablished.**_.

**Comment by bameda** [comment]
Ok, so the connection works properly.

What node version are you using?

**Comment by kapoorabhish** [comment]
$ node --version
**v6.8.1**

**Comment by juanfran** [comment]
maybe it's related to https://github.com/websockets/ws/issues/246, I've upgraded ws to the lastest version. Could you upgrade and try again?

**Comment by kapoorabhish** [comment]
@bameda 
No Luck.
I had to configure it with nginx ultimately since invitations were not working with apache2.

Even after going with nginx, Events are not working.

Getting these errors in browser console.
`"NetworkError: 426 Upgrade Required - http://example.com/events"`
`"http://example.com/api/v1/auth 400 (Bad Request)"`

@juanfran 
I upgraded the "ws" by running the command:
`$ npm install --save ws`

Still did not work. I am totally new to node, so please correct me if I did something wrong.

**Comment by bameda** [comment]
> **HTTP 426 Upgrade Required:** The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field.

I don't know but it seems there is something wrong in your setup. If you have all this problems maybe you should to use taiga-vagrant or taiga-scripts to get a clean setup and then you can customize it carefully.
