### ISSUE TITLE
Potentially unhandled rejection [1] Error: read ECONNRESET

### ISSUE THREAD

**Issue by KehaoWu** [taigaio/taiga-events#22]
It displays below message when I visit project's timeline.
```
Potentially unhandled rejection [1] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

Potentially unhandled rejection [2] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)

Potentially unhandled rejection [3] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
```

Environment:

Ubuntu 16
CoffeeScript version 1.12.3
nodejs version v6.9.4

**Comment by Zwordi** [comment]
Hello, I got the same behavior when i activate HTTPS using taiga-docs.

Please advice
(Recent install)
