### ISSUE TITLE
this not a typed array

### ISSUE THREAD

**Issue by aaron-npd** [taigaio/taiga-events#24]
Hello - 

I installed taiga-events on a fresh ubuntu 16 load.  Followed the instructions in the readme.  When I run 'coffee index.coffee' I get the following error.  Any ideas?  Thanks!

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/tmp/sob/taiga-events/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/sob/taiga-events/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/sob/taiga-events/node_modules/ws/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/sob/taiga-events/index.coffee:4:19)
    at Object.<anonymous> (/tmp/sob/taiga-events/index.coffee:1:1)
    at Module._compile (module.js:410:26)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by juanfran** [comment]
Hi, which version of Node are you using?

**Comment by aaron-npd** [comment]
node v4.2.6

More confusing is that I Iset up a taiga vm last week on ubuntu desktop 16.04 and that one is working fine.  The version of node is the same.  I did a diff between the two taiga-events directories from the two different installations.  There are some differences.  I'll paste that below.  Maybe using wrong versions of some of the dependencies?  Thanks for your help.

taiga@taiga:/tmp$ diff ~/taiga-events/ /tmp/taiga-events/
Common subdirectories: /home/taiga/taiga-events/.git and /tmp/taiga-events/.git
diff /home/taiga/taiga-events/.gitignore /tmp/taiga-events/.gitignore
5d4
< dist/
\ No newline at end of file
diff /home/taiga/taiga-events/gulpfile.js /tmp/taiga-events/gulpfile.js
6d5
< var coffee = require("gulp-coffee");
21,31d19
< });
<
< gulp.task('config', function() {
<     return gulp.src('config.json')
<         .pipe(gulp.dest('dist/'));
< });
<
< gulp.task("coffee", ['config'], function() {
<     return gulp.src("*.coffee")
<         .pipe(coffee())
<         .pipe(gulp.dest("dist/"));
Common subdirectories: /home/taiga/taiga-events/node_modules and /tmp/taiga-events/node_modules
diff /home/taiga/taiga-events/package.json /tmp/taiga-events/package.json
21d20
<     "gulp-coffee": "^2.3.3",
27c26
<     "amqplib": "^0.5.1",
---
>     "amqplib": "^0.4.1",
31c30
<     "ws": "^2.0.3"
---
>     "ws": "^1.1.1"
diff /home/taiga/taiga-events/rabbit.coffee /tmp/taiga-events/rabbit.coffee
54a55,56
>             delete pendingChannels[client_id]
>
64,67c66
<         return pendingChannels[client_id].then (ch) ->
<             delete pendingChannels[client_id]
<
<             return ch
---
>         return pendingChannels[client_id]

**Comment by bameda** [comment]
Hi @aaron-npd 

You are using an old version of node, please upgrade node to a version >= 6.0 (The current stable is 7.5.0 and the last LTS is 6.9.5 LTS).

**Comment by aaron-npd** [comment]
David -

Running v6.9.5 now - things are working a lot better!  Didn't realize that
was so hopelessly out of date.  Are there any other packages I should look
at updating?

Thanks

**Comment by bameda** [comment]
Great.

I think not.
