### ISSUE TITLE
Frontend can't establish websocket to events

### ISSUE THREAD

**Issue by m-terlinde** [taigaio/taiga-events#32]
Hey guys,

I installed taiga with help of the official guide for production systems.
But I can't manage to get the events working:
`WebSocket connection to 'ws://192.168.3.2/events' failed: WebSocket is closed before the connection is established.
stopExistingConnection — app.js:3141
r — lodash.js:4968
setupConnection — app.js:3113
r — lodash.js:4968
`

The web socket isn't reachable on the host at 127.0.0.1:8888. The 4 services are up and running.
The DNS entry for the domain isn't up currently, so I replaced the URLs in the config files with the IP.

**ngnix taiga.conf**
`server {
    listen 80 default_server;
    server_name _;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /home/taiga/logs/nginx.access.log;
    error_log /home/taiga/logs/nginx.error.log;

    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }

	# Taiga-events
	location /events {
	proxy_pass http://127.0.0.1:8888/events;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_connect_timeout 7d;
	proxy_send_timeout 7d;
	proxy_read_timeout 7d;
	}
}`

**/etc/circus/conf.d/taiga.ini**
`[watcher:taiga]
working_dir = /home/taiga/taiga-back
cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/taiga/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = /home/taiga/logs/gunicorn.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[env:taiga]
PATH = /home/taiga/.virtualenvs/taiga/bin:$PATH
TERM=rxvt-256color
SHELL=/bin/bash
USER=taiga
LANG=en_US.UTF-8
HOME=/home/taiga
PYTHONPATH=/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages`

**/etc/circus/conf.d/taiga-celery.ini**
`cat: /etc/circus/conf.d/taiga-celery.ini: No such file or directory`

**/etc/circus/conf.d/taiga-events.ini**
`[watcher:taiga-events]
working_dir = /home/taiga/taiga-events
cmd = /usr/bin/coffee
args = index.coffee
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/taiga/logs/taigaevents.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 12
stderr_stream.class = FileStream
stderr_stream.filename = /home/taiga/logs/taigaevents.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 12`

**/home/taiga/taiga-back/settings/local.py**
`from .common import *

MEDIA_URL = "http://scrum.domain.local/media/"
STATIC_URL = "http://scrum.domain.local/static/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "scrum.domain.local"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

#CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASS@localhost:5672/taiga"}

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"`

**/home/taiga/taiga-front-dist/dist/conf.json**
`{
	"api": "http://192.168.3.2/api/v1/",
	"eventsUrl": "ws://192.168.3.2/events",
	"debug": "true",
	"publicRegisterEnabled": true,
	"feedbackEnabled": true,
	"privacyPolicyUrl": null,
	"termsOfServiceUrl": null,
	"maxUploadFileSize": null,
	"contribPlugins": []
}`

**/home/taiga/taiga-events/config.json**
`{
    "url": "amqp://taiga:PASS@localhost:5672/taiga",
    "secret": "theveryultratopsecretkey",
    "webSocketServer": {
        "port": 8888
    }
}`

**taigaevents.stderr.log** (The error repeats)
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: RSV1 must be clear
    at Receiver.getInfo (/home/taiga/taiga-events/node_modules/ws/lib/Receiver.js:191:18)
    at Receiver.startLoop (/home/taiga/taiga-events/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/home/taiga/taiga-events/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/taiga/taiga-events/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)`

**gunicorn.stderr.log**
`Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
[2017-09-11 10:24:13 +0200] [1200] [INFO] Shutting down: Master
[2017-09-11 10:24:14 +0200] [2729] [INFO] Starting gunicorn 19.6.0
[2017-09-11 10:24:14 +0200] [2729] [INFO] Listening at: http://127.0.0.1:8001 (2729)
[2017-09-11 10:24:14 +0200] [2729] [INFO] Using worker: sync
[2017-09-11 10:24:14 +0200] [2747] [INFO] Booting worker with pid: 2747
[2017-09-11 10:24:14 +0200] [2748] [INFO] Booting worker with pid: 2748
[2017-09-11 10:24:15 +0200] [2749] [INFO] Booting worker with pid: 2749
[2017-09-11 10:26:38 +0200] [2729] [INFO] Handling signal: term
Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
[2017-09-11 10:26:38 +0200] [2729] [INFO] Shutting down: Master
[2017-09-11 10:30:14 +0200] [2988] [INFO] Starting gunicorn 19.6.0
[2017-09-11 10:30:14 +0200] [2988] [INFO] Listening at: http://127.0.0.1:8001 (2988)
[2017-09-11 10:30:14 +0200] [2988] [INFO] Using worker: sync
[2017-09-11 10:30:14 +0200] [3004] [INFO] Booting worker with pid: 3004
[2017-09-11 10:30:14 +0200] [3008] [INFO] Booting worker with pid: 3008
[2017-09-11 10:30:14 +0200] [3009] [INFO] Booting worker with pid: 3009`

Can you help me with that problem? 
`curl 127.0.0.1:8888/events` got me a connection refused.

Thanks in advance
Matthias

**Comment by m-terlinde** [comment]
Is there anyone who can help me?
Or do you know someone who I can ask?

**Comment by agorton-nvl** [comment]
Almost two years later, same problem continues to exist. Is there a solution for this?

**Comment by alexhermida** [comment]
@agorton-nvl I think there isn't a bug indeed but a configuration issue.

**Comment by Genysys** [comment]
Bumping this . I am using docker , which runs fine. However , when I try it on my ec2 instance I get this same issue.
