### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by paulkernstock** [taigaio/taiga-events#39]
I did a complete upgrade of Taiga from 3.0.0. to 4.0.2 last week and could not make taiga-eevents back to work while I remeber it working before the upgrade. I reinstalled the node dependecies and double-checked the configuration. I am running the services with circus and while initially all services start up fine, taiga-events crashes after some time.

`config.json`
```
{
    "url": "amqp://taiga:PASSWORD@localhost:5672/taiga",
    "secret": "SECRET_KEY",
    "webSocketServer": {
        "port": 8888
    }
}
```

The secret key matches the backend's `SECRET_KEY` and the password in the URL matches the one in the backend's `EVENTS_PUSH_BACKEND` constant in local.py.

Here's the error:
```
taiga@taiga-server:~$ coffee taiga-events/index.coffee 
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/taiga-events/logger.coffee:1:11)
    at Object.<anonymous> (/home/taiga/taiga-events/logger.coffee:1:1)
    at Module._compile (module.js:410:26)
    at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:1:10)
    at Object.<anonymous> (/home/taiga/taiga-events/index.coffee:1:1)
    at Module._compile (module.js:410:26)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
    at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by alexhermida** [comment]
@paulkernstock which node version did you use to install dependencies? 

Could you try to execute it with `$ node_modules/coffeescript/bin/coffee index.coffee`?

**Comment by paulkernstock** [comment]
@alexhermida I had node 4.2.6 installed. I updated nodejs to 10.x and reinstalled the node packages. Now events seems to remain running. Thanks for the hint. Please consider mentioning a node update in the [update guide](https://taigaio.github.io/taiga-doc/dist/#_upgrades) of Taiga.

Also, I would like to check if it is running stable. Which taiga actions are triggering events, and to whom? Thanks for your help.
