### ISSUE TITLE
Crash whenever websocket closes

### ISSUE THREAD

**Issue by LecrisUT** [taigaio/taiga-events#51]
I have just had events crash whenever it was accessed with the following error:
```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./src/index.js`
[INFO] - [2021-02-03 14:31:35]: WS server is started
[INFO] - [2021-02-03 14:31:35]: Liveness / Readiness server was started in http://localhost:3023/healthz
[INFO] - [2021-02-03 14:31:45]: New WS connection: d72be397-e240-4b58-bf20-81bc713df367
[INFO] - [2021-02-03 14:31:45]: New message: {"cmd":"auth","data":{"token":"eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjoxNn0:1l7ACz:trYyAVKTzNzxbqQ1JZ79hnq1utU","sessionId":"0c1aac87f2907b27a0c8465e0b484989b175d084"}}
[INFO] - [2021-02-03 14:31:45]: New message: {"cmd":"subscribe","routing_key":"notifications"}
[INFO] - [2021-02-03 14:31:45]: New message: {"cmd":"subscribe","routing_key":"web_notifications.16"}
[WARN] - [2021-02-03 14:31:45]: Unhandled Rejection: "Error: Expected ConnectionOpenOk; got <ConnectionClose channel:0>"
```
~~After running in `dev` mode and starting all of the services `taiga-async` and `taiga-protected` before events, for some reason I cannot recreate the error.~~ (Edit: The error is still there) If anyone else encounters this issue, maybe the root cause will be more clear.

My current web-server is caddy.

Here are some more log info
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'start:production' ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'prestart:production', 'start:production', 'poststart:production' ]
5 info lifecycle taigaio-events@6.0.0~prestart:production: taigaio-events@6.0.0
6 info lifecycle taigaio-events@6.0.0~start:production: taigaio-events@6.0.0
7 verbose lifecycle taigaio-events@6.0.0~start:production: unsafe-perm in lifecycle true
8 verbose lifecycle taigaio-events@6.0.0~start:production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/taiga/taiga-events/node_modules/.bin:/opt/taiga/.local/bin:/opt/taiga/bin:/opt/maven/apache-maven/bin:/sbin:/bin:/usr/sbin:/usr/bin
9 verbose lifecycle taigaio-events@6.0.0~start:production: CWD: /opt/taiga/taiga-events
10 silly lifecycle taigaio-events@6.0.0~start:production: Args: [ '-c', 'NODE_ENV=production node ./src/index.js' ]
11 silly lifecycle taigaio-events@6.0.0~start:production: Returned: code: 1  signal: null
12 info lifecycle taigaio-events@6.0.0~start:production: Failed to exec start:production script
13 verbose stack Error: taigaio-events@6.0.0 start:production: `NODE_ENV=production node ./src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid taigaio-events@6.0.0
15 verbose cwd /opt/taiga/taiga-events
16 verbose Linux 5.9.12-1.el8.elrepo.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "start:production"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error taigaio-events@6.0.0 start:production: `NODE_ENV=production node ./src/index.js`
22 error Exit status 1
23 error Failed at the taigaio-events@6.0.0 start:production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by LecrisUT** [comment]
I believe this is just due to a typo in the [documentation](https://taigaio.github.io/taiga-doc/dist/setup-production.html#taiga-events)
It should read as follows:
```
#RABBITMQ_URL="amqp://rabbitmquser:rabbitmqpassword@rabbitmqhost:5672"
RABBITMQ_URL="amqp://rabbitmquser:rabbitmqpassword@rabbitmqhost:5672/taiga"
```
